#!/bin/sh

# run xinitrc.d scripts
for f in /etc/X11/xinit/xinitrc.d/?*.sh; do [ -x "$f" ] && "$f"; done; unset f

# source machine-specific configs
for f in ~/.config/X11/xinitrc.d/*; do [ -r "$f" ] && . $f; done; unset f

# merge xresources
xrdb -merge ~/.config/X11/xresources &

# disable bell
xset -b &

# disable the default screen blanking
xset dpms 0 0 0 &

# enable autolocking
autolock &

# enable keyboard remaps / mouse settings
remaps &

# startup dunst
dunst-init &

# wait for tasks to finish
wait

# run and manage services and daemons via runsvdir (which is a runit tool).
# stuff like pulseaudio, mpd, aria2, transmission, dwmbar, stalonetray, etc.
runsvdir -P "$USVDIR" &

# lock the screen
sleep 0.2; lock & sleep 0.2

# set wallpaper
~/.fehbg &

# loop to launch dwm and relaunch if killed
while true; do
    dwm
done
