#!/bin/sh

# source system configs
for f in /etc/X11/xinit/xinitrc.d/?*.sh; do [ -x "$f" ] && . "$f"; done; unset f

# source machine-specific configs
for f in ~/.local/share/local/xinitrc.d/*; do [ -r "$f" ] && . $f; done; unset f

# merge xresources
xrdb -merge ~/.config/X11/xresources &

# disable the bell and DPMS
xset -b dpms 0 0 0 &

# enable autolocking
autolock &

# apply keyboard remaps / mouse settings
remaps &

# set the wallpaper
~/.fehbg &

# wait for the tasks to finish
wait

# run and manage the user services (dwmbar, stalonetray, etc.) using runsvdir
runsvdir -P ~/.local/runit/run &

# lock the screen
until pidof -q xss-lock; do sleep 0.2; done
loginctl lock-session
sleep 0.5

# loop to launch dwm and relaunch upon it's exit
while :; do
    dwm
done
