#!/bin/sh

# source system configs
for f in /etc/X11/xinit/xinitrc.d/?*.sh; do [ -x "$f" ] && . "$f"; done; unset f

# source machine-specific configs
for f in ~/.local/share/local/xinitrc.d/*; do [ -r "$f" ] && . $f; done; unset f

# merge xresources
xrdb -merge ~/.config/X11/xresources &

# disable the bell and DPMS
xset -b dpms 0 0 0 &

# enable autolocking
autolock &

# apply keyboard remaps / mouse settings
remaps &

# set the wallpaper
~/.fehbg &

# run gpg-agent and export it's ssh-agent socket
gpgconf --launch gpg-agent
gpg-connect-agent updatestartuptty /bye
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# wait for the tasks to finish
wait

# run and manage the user services (dwmbar, picom, etc.) using runsvdir
runsvdir -P ~/.local/runit/run &

while :; do
    dwm
done
