#!/bin/bash
# a file opener script for lf.
# note: sxiv's -F option requires the START_FROM_FILE_PATCH from sxiv-flexipatch,
# and the -E option requires this patch:
# https://github.com/soystemd/sxiv-flexipatch/commit/7422f2c?diff=unified

IFS=$'\n'

[ -z $id ] || [ -z $f ] && exit 1

case $1 in
    -a) f=$fx ;;
esac

# delay before exit to keep lf from crashing due to a racing issue:
# https://github.com/gokcehan/lf/issues/621#issuecomment-841576897
trap 'sleep 0.01' EXIT

printf '\e[?1049h'
printf '\e[H'

ext=true
case $(printf '%s\n' $f | tr A-Z a-z) in
    *.pro) kicad $f ;;
    *.kicad_pcb|*.kicad_pcb-bak) pcbnew $f ;;
    *.sch|*.sch-bak) eeschema $f ;;
    *.azw3|*.mobi|*.fb[23]) foliate $f ;;
    *) ext=false ;;
esac || read -p 'Press enter to continue'
[ "$ext" = true ] && exit

case $(file -b --mime-type --dereference -- $f) in
    */pdf) zathura -- $f ;;
    */epub*) foliate $f ;;
    */x-xcf|*photoshop) gimp -- $f ;;
    video/*) mpv --really-quiet -- $f ;;
    audio/*) mpvmusic -- $f ;;
    image/*) sxiv -aoEF $(realpath -- $f) .  ;;
    */x-sc) sc-im -- $f ;;
    text/*|*/json) $EDITOR -- $f ;;

    */vnd.ms*|*/msword|*/vnd.openxml*|*opendoc*|*officedoc*)
        libreoffice $f
    ;;

    */x-archive|*/x-compress|*/x-cpio|*/x-tar|*/x-bzip2|*/gzip|*/x-lz*|\
    */x-xz|*/zstd|*/x-7z*|*/x-ace*|*/x-rar*|*/x-gtar|*/zip)
        atool -lp -- $f
    ;;
esac || read -p 'Press enter to continue'
