#!/bin/bash
# a file opener script for lf.
IFS=$'\n'

[ -z $id ] || [ -z $f ] && exit 1

case $1 in
    -a) f=$fx ;;
esac

printf '\e[?1049h'
printf '\e[H'

ext=true
case $(printf '%s\n' $f | tr A-Z a-z) in
    *.pro) kicad $f ;;
    *.kicad_pcb|*.kicad_pcb-bak) pcbnew $f ;;
    *.sch|*.sch-bak) eeschema $f ;;
    *.azw3|*.mobi|*.fb[23]) zathura -- $f ;;
    *) ext=false ;;
esac || read -p 'Press enter to continue'
[ "$ext" = true ] && exit

case $(file -b --mime-type --dereference -- $f) in
    */vnd.djvu|*/pdf|*/epup*) zathura -- $f ;;
    */x-xcf|*photoshop) gimp -- $f ;;
    video/*) mpv --really-quiet -- $f ;;
    audio/*) mpvmusic -- $f ;;
    image/*) sxiv -aoF $(realpath -- $f) . | lfselect ;;
    */html) $BROWSER $f ;;
    */troff) man -- $f ;;
    */x-sc) sc-im -- $f ;;
    text/*|*/json) $EDITOR -- $f ;;

    */vnd.ms*|*/msword|*/vnd.openxml*|*opendoc*|*officedoc*)
        libreoffice $f
    ;;

    */x-archive|*/x-compress|*/x-cpio|*/x-tar|*/x-bzip2|*/gzip|*/x-lz*|\
    */x-xz|*/zstd|*/x-7z*|*/x-ace*|*/x-rar*|*/x-gtar|*/zip)
        atool -lp -- $f
    ;;
esac || read -p 'Press enter to continue'
