#!/bin/sh
case $(file -b --mime-type -- "$1") in
    text/*|*/xml) cat "$1" ;;
    image/*) sxip "$1" "$2" "$3" "$4" "$5"; exit 1 ;;
    video/*|audio/*) mediainfo "$1" ;;
    */pdf) pdftotext -l 10 -nopgbrk -q -- "$1" - ;;
    *opendocument*) odt2txt "$1" ;;
esac
