#!/bin/sh
uid() { stat -Lc '%n%i%F%s%W%Y' -- "$1" | sha256sum | cut -d' ' -f1 ;}
info() { mediainfo "$1" | sed -E 's/^((\S+ )+) +:/\1=/' ;}
type=$(file -bL --mime-type -- "$1")
case $type in
    text/*|*/xml|*/json) cat "$1" ;;
    audio/*) info "$1" ;;
    */x-7z*|*/x-rar|*/zip|*/zstd|*/x-xz|*/gzip) atool -l "$1" ;;
    image/*)
        if [ -z "$DISPLAY" ]; then
            chafa -c 240 -s "${2}x${3}" -- "$1"
            exit
        fi
        sxip "$1" "$2" "$3" "$4" "$5"
        exit 1
    ;;
    video/*)
        if [ -z "$DISPLAY" ]; then
            info "$1"
            exit
        fi
        d=~/.cache/lf
        f=$d/$(uid "$1").jpg
        mkdir -pm700 "$d"
        [ ! -f "$f" ] && ffmpegthumbnailer -s0 -q5 -f -i "$1" -o "$f"
        sxip "$f" "$2" "$3" "$4" "$5"
        exit 1
    ;;
    *) echo "[$type]"; file -bL -- "$1" | fold -sw"$2" ;;
esac
