#!/bin/sh
# cleanup pacman's cache.
set -e

# find pacman's cache dir.
cache_dir=$(grep -Pom1 '^\s*CacheDir\s*=\s*\K\S+' /etc/pacman.conf)

# set the mtime and atime of packages the same as their date of birth;
# because their date of birth represents their download date,
# but their mtime and atime does not.
printf '%s\n' "${cache_dir:?}"/* |
    xargs -P$(nproc) -d'\n' -L1 sh -c 'touch -cd@"$(stat -c%W -- "$0")" -- "$0"'

# do the cleanup using paccache.
paccache -rvk2
paccache -rvuk0 -igo,rust --min-mtime 'a month ago'
