#!/bin/sh
# this script enables dns caching using unbound.
write() {
    t=$(mktemp) || return 1
    cat >"${t:?}" || return 1
    [ -e "$1" ] && [ "$(sha256sum < "$t")" = "$(sha256sum < "$1")" ] || {
        cp "$t" "$1" && echo Updated "$1".
    }
    rm "$t"
}

# install packages
c() { command -v $1 >/dev/null ;}
c resolvconf && c unbound && [ -e /etc/runit/sv/unbound ] ||
    pacman -S --needed openresolv unbound unbound-runit || {
    echo Failed installing packages.
    exit 1
}

# enable unbound's service
e=/etc/runit/sv; r=/run/runit/service
[ -e $r/unbound ] || ln -vs $e/unbound $r || {
    echo "Failed installing unbound's service."
    exit 1
}

# set NetworkManager's resolv manager to resolvconf
printf '[main]\nrc-manager=resolvconf\n' | write /etc/NetworkManager/conf.d/dns.conf

# update resolvconf's configuration
cat << 'eof' | write /etc/resolvconf.conf
unbound_conf=/etc/unbound/resolvconf.conf
unbound_restart="sv restart unbound"
name_servers=127.0.0.1
eof

# update unbound's configuration
cat << 'eof' | write /etc/unbound/unbound.conf
include: /etc/unbound/resolvconf.conf
server:
	trust-anchor-file: /etc/unbound/trusted-key.key
	cache-max-negative-ttl: 2
eof

# add resolvconf support to windscribe vpn
f=/etc/windscribe/update-resolv.sh
cat << 'eof' | write $f && chmod 755 $f
#!/bin/bash
split_into_parts() { part1="$1"; part2="$2"; part3="$3" ;}
case "$script_type" in
    up)
        for optionvarname in ${!foreign_option_*} ; do
            option="${!optionvarname}"; echo "$option"
            split_into_parts $option
            [ "$part1" = "dhcp-option" ] && [ "$part2" = "DNS" ] &&
                echo "nameserver $part3" | resolvconf -x -a windscribe
        done
    ;;
    down) resolvconf -d windscribe; resolvconf -u; resolvconf -r unbound ;;
esac
eof
