#!/bin/sh
# this script installs elogind's logind.conf.
write() {
    t=$(mktemp) || return 1
    cat >"${t:?}" || return 1
    [ -e "$1" ] && [ "$(sha256sum < "$t")" = "$(sha256sum < "$1")" ] || {
        cp "$t" "$1" && echo Updated "$1".
    }
    rm "$t"
}

cat << 'eof' | write /etc/elogind/logind.conf
[Login]
HandleLidSwitch=lock
HandleLidSwitchExternalPower=lock
HandleLidSwitchDocked=lock
[Sleep]
HandleNvidiaSleep=no
HibernateMode=platform shutdown suspend
HibernateDelaySec=7200s
eof
