#!/bin/sh
# this script installs an rc.local file to do some stuff on startup.
write() {
    t=$(mktemp) || return 1
    cat >"${t:?}" || return 1
    [ -e "$1" ] && [ "$(sha256sum < "$t")" = "$(sha256sum < "$1")" ] || {
        cp "$t" "$1" && echo Updated "$1".
    }
    rm "$t"
}

cat << 'eof' | write /etc/rc.local
# rc.local for Artix Linux
# This file will be executed on stage 2 before running services.
setsid -f ntpd -gq >/dev/null 2>&1
setsid -f light -S 40 >/dev/null 2>&1
eof
