#!/bin/sh
# setup neomutt's folders and ask for an account to open

dir=~/.local/share/neomutt
acc=$dir/accounts

command -v abook >/dev/null ||
    notify-send NeoMutt 'Please install "abook" to get addressbook functionality'

command -v lynx >/dev/null  ||
    notify-send NeoMutt 'Please install "lynx" to be able to read HTML mails'

[ ! -d $acc ] && cat << 'eof' | { mkdir -p $acc; cat > $acc/EXAMPLE ;}
# vim:ft=neomutt
set realname  = "Rick Sanchez"
set imap_user = rickydog
set from      = $imap_user@host
set folder    = imap://$imap_user@host:1234
set smtp_url  = smtp://$imap_user@host:5678
set smtp_pass = password
set imap_pass = password
eof

mkdir -p ~/.cache/neomutt $dir/abook

! sel="$(
    for account in $acc/*; do basename $account; done |
    dmenu -w $WINDOWID -p 'Choose an Email Account'
)" && pkill -nx neomutt && exit

echo source $acc/$sel
