#!/bin/sh
# setup neomutt's folders and ask for an account to open

dir=~/.local/share/neomutt
acc=$dir/accounts

command -v abook >/dev/null ||
    notify-send NeoMutt 'Please install "abook" to get addressbook functionality'

command -v lynx >/dev/null  ||
    notify-send NeoMutt 'Please install "lynx" to be able to read HTML mails'

[ ! -d $acc ] && cat << 'eof' | { mkdir -p $acc; cat > $acc/EXAMPLE ;}
# vim:ft=neomutt
set realname  = 'James Bond'
set my_host   = host.com
set imap_user = b007nd
set from      = $imap_user@$my_host
set folder    = imap://$imap_user@$my_host:1234
set smtp_url  = smtp://$imap_user@$my_host:5678
source 'gpg -dq ~/.local/share/pass/EXAMPLE.gpg|'
set smtp_pass = $my_pass
set imap_pass = $my_pass
set spoolfile = +INBOX
set postponed = +Draft
set record    = +Sent
set trash     = +Trash
eof

mkdir -p ~/.cache/neomutt $dir/abook $dir/pass

! sel="$(
    for account in $acc/*; do basename $account; done |
    dmenu -w $WINDOWID -p 'Choose an Email Account'
)" && pkill -nx neomutt && exit

echo source $acc/$sel
