#!/bin/sh
# This script shows the description and comments of a youtube video.
# requires youtube-dl and pipe-viewer.
[ -z "$1" ] && exit 1
url=${1#ytdl://*}
comments=$(pipe-viewer --no-interactive --no-use-colors  --comments="$url")
description=$(youtube-dl -jq --no-playlist "$url" | jq -r '"Title: \(.title)","Channel: \(.channel)","\n===============\n= Description \n===============\n",.description,"\n===============\n= Comments \n==============="')
exec $TERMINAL -e sh -c 'printf "%s\n" "$@" | nvim' '' "$description" "$comments"
