#!/bin/bash
# This script shows the description and comments of an internet video.
# requires youtube-dl and pipe-viewer.
[ -z "$1" ] || [ -f "$1" ] && exit 1
url=${1#ytdl://*}
notify-send -u low mpv 'Fetching Description...'
set -o pipefail
description=$(youtube-dl -jq --no-playlist "$url" | jq -r '"Title: \(.title)","Channel: \(.channel)","\n===============\n= Description \n===============\n",.description,"\n===============\n= Comments \n==============="') || {
    notify-send mpv 'Fetching Description Failed.'
    exit 1
}
comments=$(pipe-viewer --no-interactive --no-use-colors  --comments="$url")
exec $TERMINAL -e sh -c 'printf "%s\n" "$@" | { nvim || ${PAGER:-less} ;}' '' "$description" "$comments"
