#!/bin/sh
# sxiv's key handler script.
main()
{
    exec >/dev/null 2>&1
    imgs=$(cat) # get list of images from stdin
    first=$(printf '%s\n' "$imgs" | head -n1)
    count=$(printf '%s\n' "$imgs" | wc -l)

    case "$1" in
        h) help ;;
        w) wallpaper "$first" ;;
        W) wallpaper -n "$first" ;;
        g) x setsid -f gimp -- ;;
        p) x dprint ;;
        t) ask Trash &&
            x trash-put -- &&
            notif Trashed
        ;;
        d) ask Permanently Delete &&
            x rm -- &&
            notif Deleted
        ;;
        a) ask Autorotate &&
            x jhead -autorot &&
            notif Autorotated
        ;;
        r) ask CW Rotate &&
            x -I{} convert -rotate 90 {} {} &&
            notif Rotated
        ;;
        R) ask CCW Rotate &&
            x -i{} convert -rotate -90 {} {} &&
            notif Rotated
        ;;
        f) ask Flop &&
            x -I{} convert -flop {} {} &&
            notif Flopped
        ;;
        y) xclip -selection clipboard -t \
            "$(file -bL --mime-type -- "$first")" "$first" &&
            notif 'Copied to clipboard'
        ;;
    esac
}

ask() {
    wid=$(xdotool getactivewindow)
    ans=$(printf "No\\nYes" | dmenu -p "$* $count image(s)?" ${wid:+-w $wid} \
        -nb darkred -sb maroon -sf white -nf darkgray)
    [ "$ans" = Yes ] && return 0 || return 1
}

x() { printf '%s\n' "$imgs" | xargs -d'\n' "$@" ;}
notif() { notify-send sxiv "$* $count image(s)." ;}

help() {
cat << 'eof'
y)   copy image to clipboard
a)   auto rotate based on metadata
r,R) rotate cw/ccw
f)   flip horizontally
g)   open in gimp
p)   print
w)   set as wallpaper
W)   set as wallpaper, no pywal
t)   trash
d)   permanently delete
h)   show this help message
eof
}

main "$@"
