#!/bin/sh
while :; do
    sleep 1m
    for b in /sys/class/power_supply/BAT*; do
        [ -d "$b" ] && [ "$(cat "$b/status")" != Charging ] &&
            case $(cat "$b/capacity") in [0-5]) loginctl hibernate ;; esac
    done
done
