#!/bin/bash
# hibernate the system on low battery, send warning notifcations beforehand.
notif() {
    for pid in $( pstree -Tlp | grep -A2 Xorg | grep -o '([0-9]\+)' | tr -d '()' ); do
        unset DISPLAY XAUTHORITY
        while IFS= read -r -d $'\0' env; do
            case ${env%%=*} in
                DISPLAY|XAUTHORITY) eval "$env" ;;
            esac
        done < /proc/"$pid"/environ
        [ -z "$DISPLAY" ] && continue
        export DISPLAY XAUTHORITY
        read -r user group < <(ps -o user=,group= -p "$pid")
        runuser -u "$user" -g "$group" -- notify-send -u critical 'Battery Low!' 'System will hibernate on 5% battery.'
    done
}
while :; do
    sleep 1m
    for b in /sys/class/power_supply/BAT*; do
        [ -d "$b" ] && [ "$(<"$b/status")" != Charging ] &&
            case $(<"$b/capacity") in
                [6-9]) notif ;;
                [0-5]) loginctl hibernate ;;
            esac
    done
done
